Debug "1"

GenericPunctNone ""
GenericPunctSome "--punct=\"()[]{};:\""
GenericPunctMost "--punct=\"()[]{};:\""
GenericPunctAll "--punct"

GenericExecuteSynth "env DATA="\"$DATA\"" VOICE="\"$VOICE\"" /usr/bin/piper-dispatcher"
#GenericExecuteSynth "echo \'$DATA\' | piper-tts --model /usr/share/piper-voices/\'$VOICE\'.onnx -f - | pw-play --rate 22050 --channel-map LE - "

GenericCmdDependency "piper-tts"
GenericDefaultCharset "utf-8"

