name: Build the most recently changed package
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: buildsrc
    - name: Create empty repo directory
      run: mkdir -p $GITHUB_WORKSPACE/repo
    #- uses: mutantmonkey/geschenkerbauer/builder@latest
    - uses: docker://mutantmonkey/geschenkerbauer-mutantmonkey:latest
      env:
        GNUPG_PUBKEYRING: /buildsrc/keyring.asc
        PACKAGER: geschenkerbauer on github <archpkgs+github@mutantmonkey.mx>
      container:
        volumes:
        - $GITHUB_WORKSPACE/buildsrc:/buildsrc
        - $GITHUB_WORKSPACE/repo:/repo
      with:
        args: golinx
