name: Build the most recently changed package
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: buildsrc
    - name: Create repo directory with correct owner
      run: install -d -o 1000 -g users
    #- uses: mutantmonkey/geschenkerbauer/builder@latest
    - uses: docker://mutantmonkey/geschenkerbauer-mutantmonkey:latest
      env:
        buildsrcdir: $GITHUB_WORKSPACE/buildsrc
        repodir: $GITHUB_WORKSPACE/repo
        gpgkeyring: 1
        PACKAGER: geschenkerbauer on github <archpkgs+github@mutantmonkey.mx>
      with:
        args: golinx
