name: Build updated packages
on:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - 'keyring.asc'
permissions:
  id-token: write
  contents: read
  attestations: write
  artifact-metadata: write

jobs:
  evaluate:
    name: Evaluate changed packages
    runs-on: ubuntu-24.04
    outputs:
      packages: ${{ steps.get-packages.outputs.packages }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        fetch-depth: 0
    - name: Figure out which packages have changed since the last push
      id: get-packages
      run: |
        echo "packages=["$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -v '^\(\.git\|keyring.asc\)' | sed 's/\/.*$//g' | sort -u | xargs -I{} bash -c "test -d \"{}\" && echo \"\\\"{}\\\"\"" | head -c -1 | sed -z 's/\n/,/g')"]" >> $GITHUB_OUTPUT
  build:
    name: Build
    needs: evaluate
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        pkgname: ${{ fromJSON(needs.evaluate.outputs.packages) }}
      fail-fast: false
    if: ${{ needs.evaluate.outputs.packages != '[]' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        path: buildsrc
    - name: Prepare build environment
      run: |
        sudo chown -R 1000 buildsrc
        sudo chown -R $(id -u) buildsrc/.git
        sudo install -d -o 1000 -g users repo
        echo "SOURCE_DATE_EPOCH=$(git -C buildsrc log -1 -i --pretty='format:%ct')" >> "$GITHUB_ENV"
    - name: Use geschenkerbauer to build packages
      uses: mutantmonkey/geschenkerbauer/action@8a59d3ba77a471258eabb184f846612597518d13 # main
      env:
        PACKAGER: geschenkerbauer on github <archpkgs+github@mutantmonkey.mx>
      with:
        packages: ${{ matrix.pkgname }}
    - name: Replace forbidden colon character in package filenames
      run: |
        for f in $(find . -iname '*:*'); do
          sudo mv "$f" "${f/:/__3A__}"
        done || exit 0
      working-directory: ./repo
    - name: Upload artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: build-output-${{ matrix.pkgname }}
        path: repo
    - name: Generate artifact attestation
      uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
      with:
        subject-path: 'repo/*'
