name: Build package

on:
  workflow_dispatch:
    inputs:
      pkgname:
        description: "Package to build"
        required: true
      nodeps:
        description: "Skip dependency checks (use 1 to disable dependency checks)"
        required: false

jobs:
  build:
    name: Build
    uses: $/.github/workflows/build-package-reusable.yml
    with:
      pkgname: ${{ github.event.inputs.pkgname }}
      nodeps: ${{ github.event.inputs.nodeps }}
      artifact-name: output
    permissions:
      id-token: write
      contents: read
      attestations: write
      artifact-metadata: write
