name: Build the most recently changed package
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: buildsrc
    - name: Create empty repo directory
      run: sudo install -d -o 1000 -g users ${{ github.workspace }}/repo
    - uses: mutantmonkey/geschenkerbauer@latest
      env:
        GNUPG_PUBKEYRING: ${{ github.workspace }}/buildsrc/keyring.asc
        PACKAGER: geschenkerbauer on github <archpkgs+github@mutantmonkey.mx>
      with:
        package: golinx
