name: Build package
on:
  repository_dispatch:
    types: [build-package]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: buildsrc
    - name: Create empty repo directory
      run: sudo install -d -o 1000 -g users repo
    - name: Use geschenkerbauer to build packages
      uses: mutantmonkey/geschenkerbauer/action@master
      env:
        GNUPG_PUBKEYRING: ${{ github.workspace }}/buildsrc/keyring.asc
        PACKAGER: geschenkerbauer on github <archpkgs+github@mutantmonkey.mx>
      with:
        packages: ${{ github.event.client_payload.pkgname }}
    - name: Replace forbidden colon character in package filenames
      run: |
        for f in *:*; do mv "$f" "${f/:/__3A__}"; done || exit 0
      working-directory: ./repo
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: output
        path: repo
