name: Check the AUR for updates
on:
  repository_dispatch:
    types: [check-aur-for-updates]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: buildsrc
        fetch-depth: 0
    - name: Check AUR for updates and open pull requests as needed
      uses: mutantmonkey/geschenkerbauer/update-action@master
      with:
        author_name: mutantmonkey
        author_email: 67266+mutantmonkey@users.noreply.github.com
        github_token: ${{ secrets.GITHUB_TOKEN }}
