name: Check the AUR for updates
on:
  repository_dispatch:
    types: [check-aur-for-updates]
  schedule:
  - cron:  '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Check AUR for updates and open pull requests as needed
      uses: mutantmonkey/geschenkerbauer/update-action@ab32a3bd461589c2dd6c8147b1c6c2d607b6bdf9
      with:
        author_name: mutantmonkey
        author_email: 67266+mutantmonkey@users.noreply.github.com
        github_token: ${{ secrets.GITHUB_TOKEN }}
