name: Check the AUR for updates
on:
  repository_dispatch:
    types: [check-aur-for-updates]
  schedule:
  - cron:  '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Check AUR for updates and open pull requests as needed
      uses: mutantmonkey/geschenkerbauer/actions/aur-update@4f50cd0097229d8e371dc3326effc3cffbbec4c7
      with:
        author_name: mutantmonkey
        author_email: 67266+mutantmonkey@users.noreply.github.com
        github_token: ${{ secrets.GITHUB_TOKEN }}
