name: Check PKGBUILDs using namcap
on:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - 'keyring.asc'
  workflow_dispatch:
permissions:
  contents: read

jobs:
  check:
    name: Check packages
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Check all PKGBUILDs using namcap
      uses: mutantmonkey/geschenkerbauer/actions/namcap@1c201fccb42467bfb8b647028613ce1894eee50d
