name: Check PKGBUILDs using namcap
on:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - 'keyring.asc'
  workflow_dispatch:
permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Check all PKGBUILDs using namcap
      uses: mutantmonkey/geschenkerbauer/actions/namcap@cf1fb3e99a268989dd7d476e379466d444591d3a
