name: Update package from AUR
on:
  workflow_dispatch:
    inputs:
      pkgbase:
        description: "Package base name"
        required: true
  repository_dispatch:
    types: [update-from-aur]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Update package from the AUR (workflow dispatch)
      uses: mutantmonkey/geschenkerbauer/actions/aur-update@eff395b734c0ec4b0f0690a03687230f7e68061e
      with:
        pkgbase: ${{ github.event.inputs.pkgbase }}
      if: ${{ github.event_name == 'workflow_dispatch' }}
    - name: Update package from the AUR (repository dispatch)
      uses: mutantmonkey/geschenkerbauer/actions/aur-update@eff395b734c0ec4b0f0690a03687230f7e68061e
      with:
        pkgbase: ${{ github.event.client_payload.pkgbase }}
      if: ${{ github.event_name != 'workflow_dispatch' }}
    - name: Push changes
      run: git push
