name: Update flyctl
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: write

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Configure git user
      run: |
        git config --local user.name mutantmonkey
        git config --local user.email 67266+mutantmonkey@users.noreply.github.com
    - uses: chainguard-dev/actions/setup-gitsign@58b5d1b6769b7e88dfa5c85bbc81a5a02eaca5bc
    - uses: mutantmonkey/geschenkerbauer/actions/pkgctl-update@8621cfd842121ed40235217dae5a6d323c544e8c
      working-directory: flyctl
    - name: Create Git commit
      run: |
        git add flyctl
        git commit -m "Update to latest version of flyctl"
    - name: Push changes
      run: git push
