name: Update flyctl
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: write

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: chainguard-dev/actions/setup-gitsign@58b5d1b6769b7e88dfa5c85bbc81a5a02eaca5bc
    - uses: mutantmonkey/geschenkerbauer/actions/pkgctl-update@e2e3d319a21c7ec1840cb61f66343941e26db008
      with:
        pkgbase: flyctl
    - name: Create Git commit
      run: |
        git add flyctl
        git commit -m "Update to latest version of flyctl"
    - name: Push changes
      run: git push
